<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Waste Material Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 18px; text-transform: uppercase; }
        .header p { margin: 2px; }
        
        .box { border: 1px solid #000; padding: 10px; margin-bottom: 20px; }
        .meta-table { width: 100%; margin-bottom: 20px; }
        .meta-table td { padding: 5px; }
        .label { font-weight: bold; width: 120px; }

        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
        .items-table th, .items-table td { border: 1px solid #000; padding: 8px; text-align: left; }
        .items-table th { background-color: #f0f0f0; }

        .footer { margin-top: 50px; }
        .signatures { width: 100%; margin-top: 30px; }
        .signatures td { width: 33%; vertical-align: top; padding-right: 10px; }
        .line { border-bottom: 1px solid #000; margin-top: 40px; margin-bottom: 5px; }
        .signatory-name { font-weight: bold; text-transform: uppercase; font-size: 11px;}
    </style>
</head>
<body>
    <div class="header">
        <h1>Camarines Sur II Electric Cooperative, Inc.</h1>
        <p>Del Gallego, Camarines Sur</p>
        <br>
        <h2>WASTE MATERIAL REPORT</h2>
    </div>

    <div class="box">
        <table class="meta-table">
            <tr>
                <td class="label">Report Date:</td>
                <td>{{ date('F d, Y') }}</td>
                <td class="label">Reference No:</td>
                <td>WM-{{ date('Y') }}-{{ str_pad($pcUnit->id, 5, '0', STR_PAD_LEFT) }}</td>
            </tr>
            <tr>
                <td class="label">Department:</td>
                <td>{{ $pcUnit->department->department_name ?? 'N/A' }}</td>
                <td class="label">Branch:</td>
                <td>{{ $pcUnit->branch->branch_name ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <h3>Item(s) for Disposal / Condemnation</h3>
    <table class="items-table">
        <thead>
            <tr>
                <th width="10%">Qty</th>
                <th width="10%">Unit</th>
                <th width="40%">Description</th>
                <th width="20%">Property No.</th>
                <th width="20%">Remarks / Defect</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Unit</td>
                <td>
                    <b>{{ $pcUnit->device_type }} - {{ $pcUnit->model }}</b><br>
                    <small>
                        {{ $pcUnit->device_type == 'Printer' ? 'Type' : 'Processor' }}: {{ $pcUnit->processor }}, 
                        {{ $pcUnit->device_type == 'Printer' ? 'Support' : 'RAM' }}: {{ $pcUnit->ram }}, 
                        {{ $pcUnit->device_type == 'Printer' ? 'Connectivity' : 'Storage' }}: {{ $pcUnit->storage }}
                    </small>
                </td>
                <td>{{ $pcUnit->asset_tag }}</td>
                <td>
                    <b>{{ strtoupper($pcUnit->status) }}</b><br>
                    {{ $pcUnit->remarks }}
                </td>
            </tr>
        </tbody>
    </table>

    <div class="box" style="margin-top: 20px;">
        <p><b>IS CERTIFY THAT I HAVE INSPECTED EACH AND EVERY ARTICLE ENUMERATED IN THIS REPORT AND THAT THE DISPOSITION MADE THEREOF WAS AS FOLLOWS:</b></p>
        <p>[ ] DESTROYED &nbsp;&nbsp;&nbsp; [ ] SOLD &nbsp;&nbsp;&nbsp; [ ] TO BE REPAIRED &nbsp;&nbsp;&nbsp; [ ] RETURNED TO STOCK</p>
    </div>

    <table class="signatures">
        <tr>
            <td>
                Prepared by:
                <div class="line"></div>
                <div class="signatory-name">Property Custodian</div>
            </td>
            <td>
                Inspected by:
                <div class="line"></div>
                <div class="signatory-name">Internal Auditor</div>
            </td>
            <td>
                Approved by:
                <div class="line"></div>
                <div class="signatory-name">General Manager</div>
            </td>
        </tr>
    </table>

    <div style="font-size: 10px; margin-top: 50px; text-align: center; color: #666;">
        Generated by Casureco DMS on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
