<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Certificate of Disposal</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; position: relative; }
        .header h1 { margin: 0; font-size: 16px; text-transform: uppercase; }
        .logo { position: absolute; top: 0; left: 0; width: 60px; }
        
        .meta-table { width: 100%; margin-bottom: 20px; }
        .meta-table td { padding: 4px; }
        
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .items-table th, .items-table td { border: 1px solid #000; padding: 6px; text-align: left; }
        .items-table th { background-color: #f0f0f0; text-align: center; }
        
        .signatures { width: 100%; margin-top: 40px; }
        .signatures td { width: 33%; vertical-align: top; padding-right: 10px; }
        .line { border-bottom: 1px solid #000; margin-top: 40px; margin-bottom: 5px; }
        .signatory-name { font-weight: bold; text-transform: uppercase; font-size: 11px; text-align: center; }
        .signatory-title { text-align: center; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('images/casureco-logo.png') }}" class="logo" alt="Logo">
        <h1>Camarines Sur II Electric Cooperative, Inc.</h1>
        <p>Del Gallego, Camarines Sur</p>
        <br>
        <h2>CERTIFICATE OF DISPOSAL</h2>
        <p>Date: {{ date('F d, Y') }}</p>
    </div>

    <table class="items-table">
        <thead>
            <tr>
                <th style="width: 10%;">Qty</th>
                <th style="width: 10%;">Unit</th>
                <th style="width: 40%;">Description of Articles</th>
                <th style="width: 20%;">Serial / Property No.</th>
                <th style="width: 20%;">Remarks / Condition</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="text-align: center;">1</td>
                <td style="text-align: center;">Unit</td>
                <td>
                    <b>{{ $device->brand ?? '' }} {{ $device->model ?? 'Unknown Model' }}</b><br>
                    {{ $deviceTypeLabel }}<br>
                    @if(isset($device->ip_address)) IP: {{ $device->ip_address }} @endif
                </td>
                <td style="text-align: center;">
                    {{ $device->asset_tag ?? $device->serial_number ?? $device->id }}
                </td>
                <td>
                    {{ ucfirst($device->status ?? 'Disposed') }}
                    @if(isset($device->remarks))
                        <br><i>{{ $device->remarks }}</i>
                    @endif
                </td>
            </tr>
        </tbody>
    </table>

    <div style="margin-bottom: 20px;">
        <p><strong>Certified Disposed/Archived:</strong></p>
        <p>I hereby certify that the property/equipment enumerated above has been permanently disposed of and removed from the active inventory list.</p>
    </div>

    <table class="signatures">
        <tr>
            <td>
                Requested by:
                <div class="line"></div>
                <div class="signatory-name">End User / Department Head</div>
                <div class="signatory-title">Requestor</div>
            </td>
            <td>
                Inspected by:
                <div class="line"></div>
                <div class="signatory-name">Technical/IT Support</div>
                <div class="signatory-title">Inspector</div>
            </td>
            <td>
                Approved by:
                <div class="line"></div>
                <div class="signatory-name">General Manager</div>
                <div class="signatory-title">Approving Authority</div>
            </td>
        </tr>
    </table>

    <div style="font-size: 10px; margin-top: 50px; text-align: center; color: #666;">
        Generated by Casureco DMS on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
