<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Memorandum Receipt</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 18px; text-transform: uppercase; }
        .header p { margin: 2px; }
        .logo { position: absolute; top: 0; left: 0; width: 60px; }
        
        .meta-table { width: 100%; margin-bottom: 20px; }
        .meta-table td { padding: 5px; }
        .label { font-weight: bold; width: 120px; }

        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
        .items-table th, .items-table td { border: 1px solid #000; padding: 8px; text-align: left; }
        .items-table th { background-color: #f0f0f0; }

        .footer { margin-top: 50px; }
        .signatures { width: 100%; margin-top: 50px; }
        .signatures td { width: 50%; vertical-align: top; padding-right: 20px; }
        .line { border-bottom: 1px solid #000; margin-top: 40px; margin-bottom: 5px; }
        .signatory-name { font-weight: bold; text-transform: uppercase; }
    </style>
</head>
<body>
    <div class="header">
        <!-- <img src="{{ public_path('images/casureco-logo.png') }}" class="logo"> -->
        <h1>Camarines Sur II Electric Cooperative, Inc.</h1>
        <p>Del Gallego, Camarines Sur</p>
        <br>
        <h2>MEMORANDUM RECEIPT FOR EQUIPMENT</h2>
        <p>MR No: {{ date('Y') }}-{{ str_pad($pcUnit->id, 5, '0', STR_PAD_LEFT) }}</p>
    </div>

    <table class="meta-table">
        <tr>
            <td class="label">Date Issued:</td>
            <td>{{ $pcUnit->date_assigned ? $pcUnit->date_assigned->format('F d, Y') : date('F d, Y') }}</td>
        </tr>
        <tr>
            <td class="label">Issued To:</td>
            <td style="font-weight: bold; text-transform: uppercase;">{{ $pcUnit->employee->full_name }}</td>
        </tr>
        <tr>
            <td class="label">Position:</td>
            <td>{{ $pcUnit->employee->position }}</td>
        </tr>
        <tr>
            <td class="label">Department:</td>
            <td>{{ $pcUnit->employee->department->department_name }}</td>
        </tr>
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th>Qty</th>
                <th>Unit</th>
                <th>Description / Specification</th>
                <th>Property No.</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Unit</td>
                <td>
                    <b>{{ $pcUnit->device_type }} - {{ $pcUnit->model }}</b><br>
                    {{ $pcUnit->device_type == 'Printer' ? 'Type' : 'Processor' }}: {{ $pcUnit->processor }}<br>
                    {{ $pcUnit->device_type == 'Printer' ? 'Support' : 'RAM' }}: {{ $pcUnit->ram }}<br>
                    {{ $pcUnit->device_type == 'Printer' ? 'Connectivity' : 'Storage' }}: {{ $pcUnit->storage }}<br>
                    <i>{{ $pcUnit->remarks }}</i>
                </td>
                <td>{{ $pcUnit->asset_tag }}</td>
                <td>Good</td>
            </tr>
        </tbody>
    </table>

    <p>I hereby acknowledge receipt of the above-described property/equipment which I shall use in the performance of my official duties. I perform to be fully accountable for the same and to return it in good condition upon demand or upon separation from the service.</p>

    <table class="signatures">
        <tr>
            <td>
                Issued by:
                <div class="line"></div>
                <div class="signatory-name">Admin / Property Custodian</div>
                <div>Authorized Signatory</div>
            </td>
            <td>
                Received by:
                <div class="line"></div>
                <div class="signatory-name">{{ $pcUnit->employee->full_name }}</div>
                <div>{{ $pcUnit->employee->position }}</div>
            </td>
        </tr>
    </table>

    <div style="font-size: 10px; margin-top: 50px; text-align: center; color: #666;">
        Generated by Casureco DMS on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
